<template>
    <div class="component-code">
        <div class="component-item">
            <code class="language-html" data-lang="html">
                <span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">btn-group</span><span class="np">"&gt;</span> <span class="na">role</span><span class="np">="</span><span class="s">group</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">button</span> <span class="na">id</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"</span> <span class="na">type</span><span class="np">="</span><span class="s">button</span><span class="np">"</span>
                <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--solid<span class="np">"</span></span> <span class="na">data-toggle</span><span class="np">="</span><span class="s">dropdown</span><span class="np">"</span>
                <span class="na">aria-haspopup</span><span class="np">="</span><span class="s">true</span><span class="np">"</span> <span class="na">aria-expanded</span><span class="np">="</span><span class="s">false</span><span class="np">"</span><span class="np">&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="nm">Dropdown</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">button<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-menu</span><span class="np">"&gt;</span> <span class="na">aria-labelledby</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span><br>
                <span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span><br>

                <span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">btn-group</span><span class="np">"&gt;</span> <span class="na">role</span><span class="np">="</span><span class="s">group</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">button</span> <span class="na">id</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"</span> <span class="na">type</span><span class="np">="</span><span class="s">button</span><span class="np">"</span>
                <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--pill<span class="np">"</span></span> <span class="na">data-toggle</span><span class="np">="</span><span class="s">dropdown</span><span class="np">"</span>
                <span class="na">aria-haspopup</span><span class="np">="</span><span class="s">true</span><span class="np">"</span> <span class="na">aria-expanded</span><span class="np">="</span><span class="s">false</span><span class="np">"</span><span class="np">&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="nm">Dropdown</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">button<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-menu</span><span class="np">"&gt;</span> <span class="na">aria-labelledby</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span><br>
                <span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span><br>

                <span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">btn-group</span><span class="np">"&gt;</span> <span class="na">role</span><span class="np">="</span><span class="s">group</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">button</span> <span class="na">id</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"</span> <span class="na">type</span><span class="np">="</span><span class="s">button</span><span class="np">"</span>
                <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--outline<span class="np">"</span></span> <span class="na">data-toggle</span><span class="np">="</span><span class="s">dropdown</span><span class="np">"</span>
                <span class="na">aria-haspopup</span><span class="np">="</span><span class="s">true</span><span class="np">"</span> <span class="na">aria-expanded</span><span class="np">="</span><span class="s">false</span><span class="np">"</span><span class="np">&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="nm">Dropdown</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">button<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">div</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-menu</span><span class="np">"&gt;</span> <span class="na">aria-labelledby</span><span class="np">="</span><span class="s">btnGroupDrop1</span><span class="np">"&gt;</span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">dropdown-item</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"&gt;</span><span class="nm">Dropdown Link</span><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span><br>
                <span class="np">&lt;/</span><span class="nt">div<span class="np">&gt;</span></span>
            </code>
        </div>
    </div>
</template>
