<template>
    <div class="component-code">
        <div class="component-item">
            <code class="language-html" data-lang="html">
                <span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--solid</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"</span> <span class="na">disable</span><span class="np">="</span><span class="s">disabled</span><span class="np">"&gt;</span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">ml-1</span><span class="np">"&gt;</span> <span class="nm">Loading .... </span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">spinner-border spinner-border-sm</span><span class="np">"</span> <span class="na">role</span><span class="np">="</span><span class="s">status</span><span class="np">"</span> <span class="na">aria-hidden</span><span class="np">="</span><span class="s">true</span><span class="np">"&gt;</span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>

                <span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--pill</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"</span> <span class="na">disable</span><span class="np">="</span><span class="s">disabled</span><span class="np">"&gt;</span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">ml-1</span><span class="np">"&gt;</span> <span class="nm">Loading .... </span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">spinner-border spinner-border-sm</span><span class="np">"</span> <span class="na">role</span><span class="np">="</span><span class="s">status</span><span class="np">"</span> <span class="na">aria-hidden</span><span class="np">="</span><span class="s">true</span><span class="np">"&gt;</span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>

                <span class="np">&lt;</span><span class="nt">a</span> <span class="na">class</span><span class="np">="</span><span class="s">btn nh-btn btn--default btn--outline</span><span class="np">"</span> <span class="na">href</span><span class="np">="</span><span class="s">javascript:void(0)</span><span class="np">"</span> <span class="na">disable</span><span class="np">="</span><span class="s">disabled</span><span class="np">"&gt;</span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">ml-1</span><span class="np">"&gt;</span> <span class="nm">Loading .... </span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br>&nbsp;&nbsp;&nbsp;<span class="np">&lt;</span><span class="nt">span</span> <span class="na">class</span><span class="np">="</span><span class="s">spinner-border spinner-border-sm</span><span class="np">"</span> <span class="na">role</span><span class="np">="</span><span class="s">status</span><span class="np">"</span> <span class="na">aria-hidden</span><span class="np">="</span><span class="s">true</span><span class="np">"&gt;</span><span class="np">&lt;/</span><span class="nt">span<span class="np">&gt;</span></span>
                <br><span class="np">&lt;/</span><span class="nt">a<span class="np">&gt;</span></span><br>
            </code>
        </div>
    </div>
</template>
